Importing libraries

In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np

Importing dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:,-1].values

Label Encoder

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

Categorical data handling

In [4]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [5]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

Splitting into training and test sets

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

Feature Scaling 

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Building the Artificial Neural Network

Initializing

In [8]:
ann = tf.keras.models.Sequential()

Adding the input layer and the 1st hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the second layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Compiling

In [12]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

Training the ANN model

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7703
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4527 - accuracy: 0.7956
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4275 - accuracy: 0.8056
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4176 - accuracy: 0.8112
Epoch 5/100
250/250 [==============================] - 0s 909us/step - loss: 0.4108 - accuracy: 0.8134
Epoch 6/100
250/250 [==============================] - 0s 961us/step - loss: 0.4048 - accuracy: 0.8179
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3988 - accuracy: 0.8226
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3926 - accuracy: 0.8274
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3876 - accuracy: 0.8292
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3833 - ac

Making predictions

In [14]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

1/1 [==============================] - 0s 86ms/step
[[0.03537895]]


Predict test set

In [15]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 796us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Confusion matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1513   82]
 [ 197  208]]


0.8605